const MARK_NOTIFICATIONS_BY_ID = "MARK_NOTIFICATIONS_BY_ID"
const MARK_NOTIFICATIONS_ALL = "MARK_NOTIFICATIONS_ALL"
const START_NOTIFICTIONS_POST = "START_NOTIFICTIONS_POST"
const END_NOTIFICTIONS_POST = "END_NOTIFICTIONS_POST"
const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
const START_LOGIN = "START_LOGIN"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAIL = "LOGIN_FAIL"

export default {
  MARK_NOTIFICATIONS_BY_ID,
  MARK_NOTIFICATIONS_ALL,
  START_NOTIFICTIONS_POST,
  END_NOTIFICTIONS_POST,
  GET_NOTIFICATIONS,
  START_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL
}